services:
  backend:
    container_name: song-go-serv
    image: song-go
    build: 
      context: ..
      dockerfile: build/package/Dockerfile
    depends_on:
      - storage
    ports:
      - "8080:8080"
    environment:
      - SSL_MODE=${SSL_MODE}
      - POSTGRES_URL=${POSTGRES_URL}
    env_file:
        - ../.env-compose

  storage:
    restart: always
    container_name: song-psql-serv
    image: postgres:16
    env_file:
      - ../.env-compose
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ../.database/postgresql/data:/var/lib/postgresql/data

volumes:
  postgres_data:
