services:
  backend:
    container_name: song-go-serv
    image: song-go
    build: 
      context: ..
      dockerfile: build/package/Dockerfile
    depends_on:
      - storage
    ports:
      - 8080:8080
    env_file:
        - ../.env

  storage:
    restart: always
    container_name: song-psql-serv
    image: postgres:16-alpine
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../.database/postgresql/data:/var/lib/postgresql/data

volumes:
  postgres_data:
